version: 2.1

orbs:
  architect: giantswarm/architect@4.14.2

workflows:
  build:
    jobs:
      - architect/push-to-docker:
          name: push-to-docker
          context: "architect"
          image: "docker.io/giantswarm/fluentd-cloudwatch-azure"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-to-quay
          context: "architect"
          image: "quay.io/giantswarm/fluentd-cloudwatch-azure"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-to-aliyun-master
          context: "architect"
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/fluentd-cloudwatch-azure"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # Push to Aliyun should execute for non-master branches only once manually approved.
      - aliyun-approval:
          type: approval
          filters:
            tags:
              ignore: /^v.*/

      - architect/push-to-docker:
          name: push-to-aliyun-pr
          context: "architect"
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/fluentd-cloudwatch-azure"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - aliyun-approval
          filters:
            tags:
              ignore: /^v.*/
