orbs:
  architect: giantswarm/architect@0.4.5

version: 2.1

workflows:
  build:
    jobs:
      - architect/push-to-docker-legacy:
          name: push-fluentd-cloudwatch-azure-to-quay
          image: "quay.io/giantswarm/fluentd-cloudwatch-azure"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"

      - hold-push-fluentd-cloudwatch-azure-to-aliyun-pr:
          type: approval
          # Needed to prevent job from being triggered on master branch.
          filters:
            branches:
              ignore: master

      - architect/push-to-docker-legacy:
          name: push-fluentd-cloudwatch-azure-to-aliyun-pr
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/fluentd-cloudwatch-azure"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          # Push to Aliyun should execute for non-master branches only once manually approved.
          requires:
            - hold-push-fluentd-cloudwatch-azure-to-aliyun-pr
          # Needed to prevent job being triggered for master branch.
          filters:
            branches:
              ignore: master

      # Push to Aliyun should execute without manual approval on master.
      - architect/push-to-docker-legacy:
          name: push-fluentd-cloudwatch-azure-to-aliyun-master
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/fluentd-cloudwatch-azure"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          # Needed to trigger job only on merge to master.
          filters:
            branches:
              only: master
